FROM --platform=linux/amd64 ubuntu:22.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential cmake curl unzip libtinfo-dev libncurses5-dev libz-dev

COPY . /repo
WORKDIR /repo
RUN ./build.sh

FROM ubuntu:22.04 as package
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y nodejs npm
COPY --from=builder /repo/Release-build/bin/saber /
COPY --from=builder /repo/include /include
COPY --from=builder /repo/testsuite /testsuite

